In [1]:
# 희소 행렬
import numpy as np
from scipy import sparse
matrix=np.array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 1, 0, 0, 0, 0, 0, 0, 0, 0], [3, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

# 밀집 행렬(dense array)
print(matrix)
# CSR 행렬 (compressed sparse row)
# 0이 아닌 원소만 저장하는 행렬(계산 비용이 절감됨)
matrix_sparse=sparse.csr_matrix(matrix)

[[0 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0]
 [3 0 0 0 0 0 0 0 0 0]]


In [2]:
# 희소 행렬을 출력
print(matrix_sparse)
# 1행 1열에 1이 있고
# 2행 0열에 3이 있음

  (1, 1)	1
  (2, 0)	3


In [3]:
# (data, (row_index, col_index))로 구성된 튜플을 전달
# shape 매개변수에서 0을 포함한 행렬의 전체 크기를 지정
# 원소의 행과 열을 직접 지정하여 희소 행렬 생성
matrix_sparse_2=sparse.csr_matrix(([1, 3], ([1, 2], [1, 0])), shape=(3, 10)) # ([원소], [행], [열])
print(matrix_sparse_2)
# 밀집 행렬로 변환
print(matrix_sparse_2.toarray())

  (1, 1)	1
  (2, 0)	3
[[0 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0]
 [3 0 0 0 0 0 0 0 0 0]]


In [4]:
import numpy as np
matrix=np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

print("행렬의 크기 :",matrix.shape) # 행렬의 크기
print("행렬의 원소 개수 :",matrix.size)
print("차원 :",matrix.ndim)
print("원소의 데이터 타입 :",matrix.dtype)
print("원소 하나가 차지하는 바이트 크기 :",matrix.itemsize)
print("배열 전체가 차지하는 바이트 크기 :",matrix.nbytes)
print("1차원으로 변환 →",matrix.flatten())

행렬의 크기 : (3, 4)
행렬의 원소 개수 : 12
차원 : 2
원소의 데이터 타입 : int32
원소 하나가 차지하는 바이트 크기 : 4
배열 전체가 차지하는 바이트 크기 : 48
1차원으로 변환 → [ 1  2  3  4  5  6  7  8  9 10 11 12]


In [5]:
## 난수 생성
np.random.seed(0) # 초깃값을 지정
np.random.random(3) # 0.0 ~ 1.0 사이에서 3개의 실수 난수를 생성 

array([0.5488135 , 0.71518937, 0.60276338])

In [7]:
print("0 ~ 10 사이에서 3개의 정수 난수를 생성 :",np.random.randint(0,11,3))
print()
print("1.0보다 크거나 같고 2.0보다 작은 3개의 수 선택 :",np.random.uniform(1.0,2.0,3))
print()
print("0 ~ 1 사이 2행 3열의 실수 난수1 :",np.random.random_sample((2,3)))
print()
print("0 ~ 1 사이 2행 3열의 실수 난수2 :",np.random.rand(2,3))
print("0 ~ 99 사이 10개의 정수 난수 :",np.random.randint(0,100,10))
print()
print("평균 0, 표준편차 1인 정규 분포에서 3개의 수 선택 :",np.random.normal(0.0,1.0,3))
print()
print("평균 0, 표준편차 1인 정규 분포 난수 2행 3열 :",np.random.standard_normal((2,3)))
print()
print("0 ~ 9 사이의 정수 중 랜덤하게 5번 선택 :",np.random.choice(range(0,10),5))

0 ~ 10 사이에서 3개의 정수 난수를 생성 : [1 4 9]

1.0보다 크거나 같고 2.0보다 작은 3개의 수 선택 : [1.44994999 1.61306346 1.90234858]

0 ~ 1 사이 2행 3열의 실수 난수1 : [[0.09928035 0.96980907 0.65314004]
 [0.17090959 0.35815217 0.75068614]]

0 ~ 1 사이 2행 3열의 실수 난수2 : [[0.60783067 0.32504723 0.03842543]
 [0.63427406 0.95894927 0.65279032]]
0 ~ 99 사이 10개의 정수 난수 : [ 3 76 52 78 15 20 99 58 23 79]

평균 0, 표준편차 1인 정규 분포에서 3개의 수 선택 : [ 0.04736482  0.3113635  -0.77602047]

평균 0, 표준편차 1인 정규 분포 난수 2행 3열 : [[-0.30736481 -0.36652394  1.11971196]
 [-0.45792242  0.4253934  -0.02797118]]

0 ~ 9 사이의 정수 중 랜덤하게 5번 선택 : [7 5 9 0 2]


In [16]:
# 리스트 섞기 (원본이 변경됨)
a=np.array([0,1,2,3,4])
np.random.shuffle(a)
a

array([1, 2, 4, 0, 3])

In [34]:
# 복사본을 만든 후 셔플 (원본 유지)
print(np.random.permutation(a))
print(a)

[2 4 3 1 0]
[1 2 4 0 3]
